name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      SESSION_ID: PRABATH-MD~IFVy0BAxxJa44ne
      GITHUB_AUTH_TOKEN: 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
      BOT_NUMBER: 32467410178

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: npm start
